name: CI
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      
  deploy-staging:
   name: Deploy a Staging
   needs: [build]
   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Instalar Railway CLI
       run: npm install -g @railway/cli
     - name: Desplegar a Railway (staging)
       run: railway up
       env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

